### ISSUE TITLE
README example wants formSubmitted on controller

### ISSUE THREAD

**Issue by sirvine** [sir-dunxalot/ember-easy-form-extensions#2]
I wasn't able to get the README example to work unless I added `formSubmitted: null` to the new controller.  Without it, I got `Property set failed: object in path "controller" could not be found or was destroyed.` — I guess because the Submitting mixin aliases against it?

**Comment by sir-dunxalot** [comment]
Seems like a bug to me - thanks for opening the issue! I'll look into it today or tomorrow.

**Comment by sir-dunxalot** [comment]
I noticed a few typos in the docs that might have led to this error - they were fixed with #3. The `Saving` mixin has `formSubmitted: false` so if that's mixed into the associated controller you shouldn't get the error. I wasn't able to replicate the issue otherwise.

Please let me know if the issue still persists with the latest version and docs.
