### ISSUE TITLE
Merge patch for 1.10 support upstream

### ISSUE THREAD

**Issue by f3ndot** [sir-dunxalot/ember-easy-form-extensions#6]
I think many people would benefit from you submitting a PR to dockyard/ember-easy-form that incorporates just the patch work required to make Easy Form work with 1.10. I'm sure @rwjblue would be more than happy to merge that.

Is that something you'd be comfortable doing?

**Comment by rwjblue** [comment]
Yeah, would be great to get the 1.10 required changes upstream so others can update to 1.10. Then this lib can layer its additional API/changes on top of that...

**Comment by bcardarella** [comment]
@sir-dunxalot if there are patches that are independent of ember-cli it would be great if you could patch back to dockyard/ember-easy-form

**Comment by sir-dunxalot** [comment]
Hey guys, thanks for the comments. I can probably get a patch put together but barely have a minute to spare right now. I wouldn't be offended if anyone just took the code from this and patched easy-form. Otherwise, I'll try and get a PR up by the end of the weekend.

I saw a bunch of patches added to easy-form/master by @rwjblue. Are there some specific blockers which haven't been addressed on master branch yet? If you're uncertain I can just play around with it.

**Comment by sir-dunxalot** [comment]
With the continuous deprecations being brought in by new Ember versions, I deemed it more maintainable to rewrite Easy Form for Ember CLI from scratch. It's a slight detachment from the original API but contains what I believe to be some improvements whilst meeting new Ember CLI resolver standards.

[You can see the first prerelease here](https://github.com/sir-dunxalot/ember-easy-form-extensions/releases/tag/1.0.0.beta). It's early stage and doesn't have test coverage yet.

**Comment by sir-dunxalot** [comment]
I should add that feedback would be appreciated from anyone trying to use Easy Form with Ember 1.11+.

**Comment by sir-dunxalot** [comment]
Closing with Easy Form's `1.0.0.rc-1` release and this library's `2.0.0` release (#48).
